name: Unified Dogfooding scans
on:
  schedule:
    - cron: "0 4 * * *" # Run the workflow every day at 04:00 UTC
  workflow_dispatch:

jobs:
  unified-platform-dogfooding:
    runs-on: github-ubuntu-latest-s
    name: Unified Platform Dogfooding
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Run IRIS Analysis
        uses: SonarSource/unified-dogfooding-actions/run-iris@v1
        with:
          primary_project_key: SonarSource_cookiecutter-sonar_1057b558-cc05-44b4-b026-6a753112a87d
          primary_platform: SQC-EU
          shadow1_project_key: SonarSource_cookiecutter-sonar_1057b558-cc05-44b4-b026-6a753112a87d
          shadow1_platform: Next
          shadow2_project_key: SonarSource_cookiecutter-sonar_1057b558-cc05-44b4-b026-6a753112a87d
          shadow2_platform: SQC-US
